"""autogenerate migrations

Revision ID: 38b90cea8fa1
Revises: 
Create Date: 2025-06-03 18:41:37.809301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b90cea8fa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('fund_type', sa.String(length=40), nullable=False),
    sa.Column('share_value', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(precision=14, asdecimal=2), nullable=False),
    sa.Column('share_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tx_type', sa.Enum('APORTE', 'RESGATE', name='tx_type'), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('fund')
    # ### end Alembic commands ###
