"""autogenerate migrations

Revision ID: 8a19c08f3d5c
Revises: beae8da310c9
Create Date: 2025-06-04 04:46:57.409968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a19c08f3d5c'
down_revision = 'beae8da310c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.alter_column('share_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=14, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(precision=14, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.alter_column('share_value',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
